title: orreksu
description: Personal page of Oleks

remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - pages/about.md
  - pages/dev.md
  - pages/misc.md

style: dark
listen_for_clients_preferred_style: true

footer: '<a href="https://github.com/orreksu">github</a> <a href="https://mas.to/@orreksu">mastodon</a>'
