title: orreksu
description: my space

remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - about.md

style: dark
listen_for_clients_preferred_style: true

footer: 'follow me on <a href="https://mas.to/@orreksu">mastodon</a>'
